### ISSUE TITLE
BIBSnet attempting to write a file (postprocessing.json) within the pretrained model folder in container

### ISSUE THREAD

**Issue by tjhendrickson** [DCAN-Labs/BIBSnet-deprecated#3]
BIBSNet has this strange requirement where it wants to write a JSON file (postprocessing.json) into the container. The upside is that this does not prevent the segmentations from being created, however, I'm afraid that it could cause the pipeline to terminate if it is run non-interactively. 
`Traceback (most recent call last):
  File "/opt/conda/bin/nnUNet_predict", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_predict')())
  File "/home/nnUNet/nnunet/inference/predict_simple.py", line 217, in main
    predict_from_folder(model_folder_name, input_folder, output_folder, folds, save_npz, num_threads_preprocessing,
  File "/home/nnUNet/nnunet/inference/predict.py", line 658, in predict_from_folder
    return predict_cases(model, list_of_lists[part_id::num_parts], output_files[part_id::num_parts], folds,
  File "/home/nnUNet/nnunet/inference/predict.py", line 277, in predict_cases
    shutil.copy(pp_file, os.path.abspath(os.path.dirname(output_filenames[0])))
  File "/opt/conda/lib/python3.8/shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/opt/conda/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/opt/nnUNet/nnUNet_raw_data_base/nnUNet_trained_models/nnUNet/3d_fullres/Task512_BCP_ABCD_Neonates_SynthSegDownsample/nnUNetTrainerV2__nnUNetPlansv2.1/postprocessing.json'
Traceback (most recent call last):
  File "/home/bibsnet/run.py", line 178, in <module>
    main()
  File "/home/bibsnet/run.py", line 25, in main
    run_nnUNet_predict(cli_args)
  File "/home/bibsnet/run.py", line 39, in run_nnUNet_predict
    subprocess.check_call((cli_args["nnUNet"],
  File "/opt/conda/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('/opt/conda/bin/nnUNet_predict', '-i', '/input', '-o', '/output', '-t', '512', '-m', '3d_fullres')' returned non-zero exit status 1.`

**Comment by GregConan** [comment]
[Just pushed a fix](https://github.com/DCAN-Labs/BIBSnet/commit/4b8d9c176f58a4d74f13a4229f65519ecbb41dbb) so `run.py` will finish without error if nnUNet_predict creates segmentation files. We can close this issue off after successfully testing the fix.

**Comment by audreymhoughton** [comment]
I believe this has been fixed with @GregConan 's edits and @tjhendrickson modifications to the dockerfile
